apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: haimgoldfisher/kafka_consumer:latest
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
        - name: KAFKA_TOPIC
          value: analytics_topic
        - name: BACKEND_URL
          value: http://flask-app:5050/events
        - name: MONGO_URI
          value: mongodb://mongo:27017/
        - name: MONGO_DB
          value: Google-Maps-Restaurant
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "ps aux | grep -v grep | grep kafka_consumer || exit 1"
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5